### ISSUE TITLE
Finish final report

### ISSUE THREAD

**Issue by verolero86** [inzamam1190/Lancaster_Barnstormers_DSE511#18]
Need to have sections describing:

- [x] kNN implementation
- [x] SVM implementation
- [x] RandomForest implementation
- [x] kNN results
- [x] SVM results
- [x] RandomForest results
- [x] Add summary and conclusions

**Comment by verolero86** [comment]
I've added a section in the google doc for knn implementation.

**Comment by inzamam1190** [comment]
@verolero86 Can you share the link for the google doc?

**Comment by verolero86** [comment]
@Harry-Long created it and shared it via UTK Google Drive: https://docs.google.com/document/d/1jvIK2V_Sxn-hVQJklMmeZTopeXlSeEJvZQcJod_FFTE/edit?usp=sharing

**Comment by verolero86** [comment]
I've added some of the results obtained for knn with k=5 to the report.

**Comment by verolero86** [comment]
All the pieces are now in the report! Good job all!
